"""empty message

Revision ID: 4d786858e08b
Revises:
Create Date: 2026-03-28 01:51:12.697052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d786858e08b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AiNews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pictureUrl", sa.String(), nullable=True),
        sa.Column("addingDate", sa.Date(), nullable=False),
        sa.Column("dropDate", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "title_drop_index_AI", "AiNews", ["title", "dropDate"], unique=False
    )
    op.create_table(
        "CryptoCurrency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pictureUrl", sa.String(), nullable=True),
        sa.Column("addingDate", sa.Date(), nullable=False),
        sa.Column("dropDate", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "title_drop_index_crypto",
        "CryptoCurrency",
        ["title", "dropDate"],
        unique=False,
    )
    op.create_table(
        "ItTechnologies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pictureUrl", sa.String(), nullable=True),
        sa.Column("addingDate", sa.Date(), nullable=False),
        sa.Column("dropDate", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "title_drop_index_IT",
        "ItTechnologies",
        ["title", "dropDate"],
        unique=False,
    )
    op.create_table(
        "Science",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pictureUrl", sa.String(), nullable=True),
        sa.Column("addingDate", sa.Date(), nullable=False),
        sa.Column("dropDate", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "title_drop_index_science",
        "Science",
        ["title", "dropDate"],
        unique=False,
    )
    op.create_table(
        "Sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pictureUrl", sa.String(), nullable=True),
        sa.Column("addingDate", sa.Date(), nullable=False),
        sa.Column("dropDate", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "title_drop_index_sports",
        "Sports",
        ["title", "dropDate"],
        unique=False,
    )
    op.create_table(
        "WorldNews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("pictureUrl", sa.String(), nullable=True),
        sa.Column("addingDate", sa.Date(), nullable=False),
        sa.Column("dropDate", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "title_drop_index_news",
        "WorldNews",
        ["title", "dropDate"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("title_drop_index_news", table_name="WorldNews")
    op.drop_table("WorldNews")
    op.drop_index("title_drop_index_sports", table_name="Sports")
    op.drop_table("Sports")
    op.drop_index("title_drop_index_science", table_name="Science")
    op.drop_table("Science")
    op.drop_index("title_drop_index_IT", table_name="ItTechnologies")
    op.drop_table("ItTechnologies")
    op.drop_index("title_drop_index_crypto", table_name="CryptoCurrency")
    op.drop_table("CryptoCurrency")
    op.drop_index("title_drop_index_AI", table_name="AiNews")
    op.drop_table("AiNews")
    # ### end Alembic commands ###
